[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_AZURE_OPENAI_API_KEY = ""
  NEXT_PUBLIC_AZURE_OPENAI_ENDPOINT = ""
  NEXT_PUBLIC_AZURE_OPENAI_DEPLOYMENT_ID = "gpt-4"

  APEXBASE_GSB_API_URL = "https://dev1.gsbapps.net"
  APEXBASE_GSB_TENANT_CODE = "apexbase"

[images]
  remote_images = ["*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
