[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_AZURE_OPENAI_API_KEY = ""
  NEXT_PUBLIC_AZURE_OPENAI_ENDPOINT = ""
  NEXT_PUBLIC_AZURE_OPENAI_DEPLOYMENT_ID = "gpt-4"

  NEXT_PUBLIC_GSB_BASE_DOMAIN = "gsbapps.net"
  NEXT_PUBLIC_DEFAULT_TENANT_CODE = "apexbase"
  NEXT_PUBLIC_GSB_COMMON_TENANT = "common"

[images]
  remote_images = ["*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
